### ISSUE TITLE
HTTP status code 415

### ISSUE THREAD

**Issue by fnobilia** [RADAR-CNS/RADAR-Commons#15]
The new `unsafe sender` returns `HTTP 415 Unsupported Media Type` while requesting `https://localhost/kafka/topics/schemaless-value`.

WARN  - Schema for android_empatica_e4_acceleration value was not yet added to the schema registry. [org.radarcns.producer.SchemaRetriever:185] 
WARN  - Schema for android_empatica_e4_acceleration value was not yet added to the schema registry. [org.radarcns.producer.SchemaRetriever:185] 
INFO  - Accept: application/vnd.kafka.v2+json, application/vnd.kafka+json, application/json
 [org.radarcns.producer.rest.RestSender:245] 
INFO  - Request{method=POST, url=https://localhost/kafka/topics/schemaless-value, tag=null} [org.radarcns.producer.rest.RestSender:246] 
ERROR - FAILED to transmit message: {"error_code":415,"message":"HTTP 415 Unsupported Media Type"} -> {"key_schema":"{\"type\":\"record\",\"name\":\"MeasurementKey\",\"namespace\":\"org.radarcns.key\",\"doc\":\"Measurement key in the RADAR-CNS project\",\"fields\":[{\"name\":\"userId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\"... [org.radarcns.producer.rest.RestSender:258] 
ERROR - FAILED to transmit message: {"key_schema":"{\"type\":\"record\",\"name\":\"MeasurementKey\",\"namespace\":\"org.radarcns.key\",\"doc\":\"Measurement key in the RADAR-CNS project\",\"fields\":[{\"name\":\"userId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\"... [org.radarcns.producer.rest.RestSender:264] 

`
java.io.IOException: Failed to submit (HTTP status code 415): {"error_code":415,"message":"HTTP 415 Unsupported Media Type"}
	at org.radarcns.producer.rest.RestSender$RestTopicSender.send(RestSender.java:260)
	at org.radarcns.producer.rest.BatchedKafkaSender$BatchedKafkaTopicSender.send(BatchedKafkaSender.java:88)
	at org.radarcns.mock.MockFile.send(MockFile.java:107)
	at org.radarcns.mock.MockProducer.start(MockProducer.java:136)
	at org.radarcns.pipeline.EndToEndTest.streamToKafka(EndToEndTest.java:283)
	at org.radarcns.pipeline.EndToEndTest.endToEnd(EndToEndTest.java:98)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	Suppressed: java.io.IOException: Failed to submit (HTTP status code 415): {"error_code":415,"message":"HTTP 415 Unsupported Media Type"}
		at org.radarcns.producer.rest.RestSender$RestTopicSender.send(RestSender.java:260)
		at org.radarcns.producer.rest.BatchedKafkaSender$BatchedKafkaTopicSender.flush(BatchedKafkaSender.java:128)
		at org.radarcns.producer.rest.BatchedKafkaSender$BatchedKafkaTopicSender.close(BatchedKafkaSender.java:137)
		at org.radarcns.mock.MockFile.send(MockFile.java:113)
		... 25 more
`

**Comment by blootsvoets** [comment]
Good catch, I'll make a hotfix. Btw this solved by moving to confluent 3.2.x but it is better to be backwards compatible.

**Comment by fnobilia** [comment]
Have you encountered issues with the self signed certificate too? b607bb9 there is a workaround for that issue too. You have a better knowledge than me about this repo, could you take a look?

**Comment by blootsvoets** [comment]
Not yet, I've used the letsencrypt valid certificate so far. That commit looks very promising, I'll take a look.

**Comment by blootsvoets** [comment]
Fixed with 0b1733593063c05fcbd6a5af89eb045fcf3da06c.
